spring:
  application:
    name: tasca-avaluacio

  datasource:
    driver-class-Name: org.h2.Driver
    url: jdbc:h2:mem:testBD
    username: dam
    password:

  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console